# Generated by Django 6.0 on 2025-12-13 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("total_rows", models.IntegerField(null=True)),
                ("processed_rows", models.IntegerField(default=0)),
                ("failed_rows", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NGOReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ngo_id", models.CharField(max_length=100)),
                ("month", models.CharField(max_length=7)),
                ("people_helped", models.IntegerField()),
                ("events_conducted", models.IntegerField()),
                (
                    "funds_utilized",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("ngo_id", "month")},
            },
        ),
    ]
